[package]
name = "camp-crm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
prost = {worksapce = true}
prost-types = {workspace = true}
anyhow = {workspace = true}
tonic = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
tokio = {workspace = true}

[build-dependencies]
tonic-build = {workspace = true}
anyhow = {workspace = true}
